#pragma once

enum OBJID { OBJ_LEVEL, OBJ_PLAYER, OBJ_AI, OBJ_UNIT, OBJ_DECO, OBJ_UI, OBJ_END };
enum OBJSTATE { STATE_PLAY, STATE_WAIT, STATE_DESTROY };
enum OBJLAYER { LAYER_BACK, LAYER_OBJ, LAYER_EFFECT, LAYER_UI, LAYER_END };

enum TEXTYPE { TEX_SINGLE, TEX_MULTI, TEX_ATLAS };

enum TEAMID { TEAM_RED, TEAM_BLUE, TEAM_GREEN, TEAM_YELLO, TEAM_END };

enum SCENEID { SCENE_LOGO, SCENE_TITLE, SCENE_STAGE_1, SCENE_STAGE_2, SCENE_STAGE_3 };

enum COMMANDER_OPERATOR { OPERATOR_PLAYER, OPERATOR_AI };